### ISSUE TITLE
Typo in 3.10. P8

### ISSUE THREAD

**Issue by capsulecorplab** [opencaesar/oml-tutorials#2]
`3.10. P8: Interface joins Interface` in http://www.opencaesar.io/oml-tutorials/#tutorial2-p8 should read `3.10. P8: Junction joins Interface`

**Comment by melaasar** [comment]
I think the title of the subsection is correct as it follows the other patterns' convention of using the `forward` relation name. `Junction` is the name of the relation entity, but `joins` is the name of the `forward` relation. This is an example of how the `relation entity` (reified relation) name does not necessarily have to be similar to the (unreified) `forward` name.
